// <auto-generated />
using LibreriaAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibreriaAPI.Migrations
{
    [DbContext(typeof(LibreriaContext))]
    partial class LibreriaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibreriaAPI.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Historias de amor y relaciones.",
                            Nombre = "Romance"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Mundos fantásticos, magia y aventuras.",
                            Nombre = "Fantasía"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Obras reconocidas de la literatura universal.",
                            Nombre = "Literatura Clásica"
                        });
                });

            modelBuilder.Entity("LibreriaAPI.Models.Libreria", b =>
                {
                    b.Property<int>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLibro"));

                    b.Property<string>("Autor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ImagURL")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("NombreLibro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdLibro");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Libreria", (string)null);

                    b.HasData(
                        new
                        {
                            IdLibro = 1,
                            Autor = "Jojo Moyes",
                            CategoriaId = 1,
                            Descripcion = "Una emotiva historia de amor.",
                            ImagURL = "/imagenes/yo-antes-de-ti.jpg",
                            NombreLibro = "Yo Antes de Ti",
                            Precio = 429.00m
                        },
                        new
                        {
                            IdLibro = 2,
                            Autor = "John Green",
                            CategoriaId = 1,
                            Descripcion = "Una historia de amor inolvidable.",
                            ImagURL = "/imagenes/bajo-la-misma-estrella.jpg",
                            NombreLibro = "Bajo la Misma Estrella",
                            Precio = 399.00m
                        },
                        new
                        {
                            IdLibro = 3,
                            Autor = "Nicholas Sparks",
                            CategoriaId = 1,
                            Descripcion = "Un romance que desafía el tiempo.",
                            ImagURL = "/imagenes/el-diario-de-noah.jpg",
                            NombreLibro = "El Diario de Noah",
                            Precio = 450.00m
                        },
                        new
                        {
                            IdLibro = 4,
                            Autor = "J. R. R. Tolkien",
                            CategoriaId = 2,
                            Descripcion = "La aventura de Bilbo Bolsón.",
                            ImagURL = "/imagenes/el-hobbit.jpg",
                            NombreLibro = "El Hobbit",
                            Precio = 390.00m
                        },
                        new
                        {
                            IdLibro = 5,
                            Autor = "J. K. Rowling",
                            CategoriaId = 2,
                            Descripcion = "El inicio de la saga de Harry Potter.",
                            ImagURL = "/imagenes/harry-potter-1.jpg",
                            NombreLibro = "Harry Potter y la Piedra Filosofal",
                            Precio = 450.00m
                        },
                        new
                        {
                            IdLibro = 6,
                            Autor = "C. S. Lewis",
                            CategoriaId = 2,
                            Descripcion = "Viaje al mágico mundo de Narnia.",
                            ImagURL = "/imagenes/narnia.jpg",
                            NombreLibro = "Las Crónicas de Narnia",
                            Precio = 480.00m
                        },
                        new
                        {
                            IdLibro = 7,
                            Autor = "Miguel de Cervantes",
                            CategoriaId = 3,
                            Descripcion = "Obra maestra de Miguel de Cervantes.",
                            ImagURL = "/imagenes/don-quijote.jpg",
                            NombreLibro = "Don Quijote de la Mancha",
                            Precio = 350.00m
                        },
                        new
                        {
                            IdLibro = 8,
                            Autor = "Jane Austen",
                            CategoriaId = 3,
                            Descripcion = "Clásico de Jane Austen.",
                            ImagURL = "/imagenes/orgullo-prejuicio.jpg",
                            NombreLibro = "Orgullo y Prejuicio",
                            Precio = 320.00m
                        },
                        new
                        {
                            IdLibro = 9,
                            Autor = "Herman Melville",
                            CategoriaId = 3,
                            Descripcion = "La búsqueda de la legendaria ballena blanca.",
                            ImagURL = "/imagenes/moby-dick.jpg",
                            NombreLibro = "Moby Dick",
                            Precio = 410.00m
                        },
                        new
                        {
                            IdLibro = 10,
                            Autor = "Gabriel García Márquez",
                            CategoriaId = 3,
                            Descripcion = "Obra cumbre del realismo mágico.",
                            ImagURL = "/imagenes/cien-anos-soledad.jpg",
                            NombreLibro = "Cien Años de Soledad",
                            Precio = 530.00m
                        });
                });

            modelBuilder.Entity("LibreriaAPI.Models.Libreria", b =>
                {
                    b.HasOne("LibreriaAPI.Models.Categoria", "Categoria")
                        .WithMany("Librerias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("LibreriaAPI.Models.Categoria", b =>
                {
                    b.Navigation("Librerias");
                });
#pragma warning restore 612, 618
        }
    }
}
