// <auto-generated />
using LibreriaAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibreriaAPI.Migrations
{
    [DbContext(typeof(LibreriaContext))]
    partial class LibreriaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibreriaAPI.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC07A0D9B1F3");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("LibreriaAPI.Models.Libreria", b =>
                {
                    b.Property<int>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLibro"));

                    b.Property<string>("Autor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Autor");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("ImagURL")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ImagURL");

                    b.Property<string>("NombreLibro")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NombreLibro");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Precio");

                    b.HasKey("IdLibro")
                        .HasName("PK__Libreria__3214EC07D9A1B0C3");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Libreria", (string)null);
                });

            modelBuilder.Entity("LibreriaAPI.Models.Libreria", b =>
                {
                    b.HasOne("LibreriaAPI.Models.Categoria", "Categoria")
                        .WithMany("Librerias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Libreria__Catego__3B75D760");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("LibreriaAPI.Models.Categoria", b =>
                {
                    b.Navigation("Librerias");
                });
#pragma warning restore 612, 618
        }
    }
}
